app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import db, login_manager

roles = {
	"admin": 1,
	"user":  2
}

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(1000), unique=True)
    password_hash = db.Column(db.String(1000))
    name = db.Column(db.String(1000))
    role = db.Column(db.Integer)
    last_audio = db.Column(db.Integer)
    seed = db.Column(db.String(1000))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_babel import _
from flask_babel import lazy_gettext as _l
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms import RadioField, SubmitField

class VoteForm(FlaskForm):
  score = RadioField(_l('Avaliação'), choices = [1, 2, 3, 4, 5],  validators=[DataRequired()])
  submit_next = SubmitField(_l('Próximo'))

class PageForm(FlaskForm):
  submit_prev = SubmitField(_l('Anterior'))

app/__init__.py
import os
from boto3 import resource, client
from pyrebase import initialize_app

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config
from config import Config


bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.login_view = 'auth.login'

s3_resource = resource(
    "s3",
    aws_access_key_id=os.environ.get("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.environ.get("AWS_SECRET_ACCESS_KEY")
)

s3_client = client(
    "s3",
    aws_access_key_id=os.environ.get("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.environ.get("AWS_SECRET_ACCESS_KEY")
)

bucket = s3_resource.Bucket(os.environ.get("S3_BUCKET"))

audio_filepaths_orig =  list(bucket.objects.all())
max_lenth = len(audio_filepaths_orig)

# Initialize firebase application and set the realtime database
firebase = initialize_app(Config.FIREBASE_CONFIG)
firebase_db = firebase.database()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .main.views import multilingual

    app.register_blueprint(multilingual)


    if app.config['SSL_REDIRECT']:
        from flask_sslify import SSLify
        sslify = SSLify(app)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import glob
import random
from io import BytesIO
from datetime import datetime
from pathlib import Path

import pyrebase
from flask_babel import _
from boto3 import resource, client
from flask_login import login_required, current_user
from flask import Blueprint, render_template, send_from_directory, send_file, session, url_for, redirect, flash, g

from config import Config
from . import main
from .forms import VoteForm, PageForm
from .. import (
  bucket, s3_resource,
  s3_client, firebase_db,
  audio_filepaths_orig, max_lenth, db
)

multilingual = Blueprint('multilingual', __name__, template_folder='templates', url_prefix='/<lang_code>')

@multilingual.url_defaults
def add_language_code(endpoint, values):
    values.setdefault('lang_code', g.lang_code)

@multilingual.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.lang_code = values.pop('lang_code')

@main.route('/sound_test', methods=['GET', 'POST'])
@login_required
def sound_test():
  return render_template('sound_test.html', s3_client=s3_client, os=os)


@main.route('/introduction', methods=['GET', 'POST'])
@login_required
def introduction():
  return render_template('introduction.html')


@main.route('/', methods=['GET', 'POST'])
@login_required
def hello():
  # Make a copy of the audio paths for further processing
  audio_filepaths = audio_filepaths_orig[:]
  # Vote form, with the 'next' button
  vote_form = VoteForm()
  # Form used to introduce the 'previous' button
  page_form = PageForm()

  # First access to the application
  if current_user.seed == None and current_user.last_audio == None:
    # Set seed to shuffle audio filepaths
    session['seed'] = datetime.now()
    current_user.seed = session['seed']

    # Set index
    session['idx'] = 0
    current_user.last_audio = session['idx']

    # Saves seed and index in the local database
    db.session.add(current_user)
    db.session.commit()
    return redirect(url_for('main.hello'))
  else:
    session['seed'] = current_user.seed
    session['idx'] = current_user.last_audio

  # Shuffle audio file paths
  random.Random(session['seed']).shuffle(audio_filepaths)

  audio_filepaths = audio_filepaths[:int(Config.MAX_SAMPLES)]

  # Message after the evaluation of all samples
  if session['idx'] >= max_lenth:
    flash(_('Votação concluida com sucesso'), 'success')

  # 'previous' button
  if page_form.validate_on_submit() and page_form.submit_prev.data == True:
    # The index is subtracted if the 'previous' button is pressed
    session['idx'] -= 1
    current_user.last_audio = session['idx']
    db.session.add(current_user)
    db.session.commit()
    return redirect(url_for('main.hello'))

  elif vote_form.validate_on_submit():
    # Saves user's score into the firebase's realtime database
    score_data = {"score": vote_form.score.data}
    firebase_db.child(f"audio/{os.path.basename(audio_filepaths[session['idx']].key.split('.wav')[0])}/id_{current_user.id}").set(score_data)
    # Iterate the index and saves in the database
    session['idx'] += 1
    current_user.last_audio = session['idx']
    db.session.add(current_user)
    db.session.commit()
    return redirect(url_for('main.hello'))

  return render_template('home.html', vote_form=vote_form, page_form=page_form, session=session, max_lenth=len(audio_filepaths), audio_filepaths=audio_filepaths, s3_client=s3_client)

app/templates/base.html
<!DOCTYPE html>
<html>

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- CSS code -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

    <!-- Activate nav-item -->
    <script>
      var toastElList = [].slice.call(document.querySelectorAll('.toast'))
      var toastList = toastElList.map(function (toastEl) {
        return new bootstrap.Toast(toastEl, option)
      })
    </script>

    <title>{{_('Avaliação de Qualidade')}}</title>
  </head>

  <body>
    <nav class="shadow navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container">
        <!-- Navbar Brand -->
        <a class="navbar-brand" href="#">{{_('Avaliação')}}</a>
        {% if current_user.is_authenticated %}
          <!-- Navbar collapse button -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!-- Navbar right side -->
          <div class="collapse navbar-collapse" id="navbarToggle">
            <ul class="navbar-nav me-auto">
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.hello') }}">{{_('Home')}}</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.introduction') }}">{{_('Instruções')}}</a></li>
            </ul>
            <ul class="navbar-nav ms-auto">
              <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.change_password') }}">{{_('Alterar Senha')}}</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
            </ul>
          </div>
        {%endif%}
      </div>
    </nav>

    <div role="main" class="container">
      <!-- Deal with flash messages of different types -->
      {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
          <div class="row justify-content-md-center">
            <div class="col-md-4">
              {% for category, message in messages %}
                {%if category not in ['error', 'warning', 'success', 'info']%}
                  <div class="alert alert-warning alert-dismissible fade show text-md-center" role="alert">
                  {%else%}
                    <div class="alert alert-{{category}} alert-dismissible fade show text-md-center" role="alert">
                {%endif%}
                  {%if category != 'success' and category != 'info'%}
                    <i class="bi bi-exclamation-triangle-fill"></i>
                  {%else%}
                    <i class="bi bi-check-circle-fill"></i>
                  {%endif%}
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              {%endfor%}
            </div>
          </div>
        {% endif %}
      {% endwith %}
    </div>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

app/templates/home.html
{% extends "base.html"%}
{% block content %}
  {%if session['idx'] < max_lenth%}
    <!-- Score Table -->
    <div class="container">
      <div class="mb-3 row justify-content-md-center">
        <div class="col-md-6">
          <table class="shadow-sm table table-bordered bg-white">
            <thead>
              <tr>
                <th style="text-align:center">{{_('Avaliação')}}</th>
                <th style="text-align:center">{{_('Qualidade')}}</th>
                <th>{{_('Distorção')}}</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style="text-align:center">5</td>
                <td>{{_('Excelente')}}</td>
                <td>{{_('Imperceptível')}}</td>
              </tr>

              <tr>
                <td style="text-align:center">4</td>
                <td>{{_('Boa')}}</td>
                <td>{{_('Apenas perceptível, mas não irritante')}}</td>
              </tr>

              <tr>
                <td style="text-align:center">3</td>
                <td>{{_('Razoável')}}</td>
                <td>{{_('Perceptível e ligeiramente irritante')}}</td>
              </tr>

              <tr>
                <td style="text-align:center">2</td>
                <td>{{_('Pobre')}}</td>
                <td>{{_('Irritante, mas não inutilizável')}}</td>
              </tr>

              <tr>
                <td style="text-align:center">1</td>
                <td>{{_('Ruim')}}</td>
                <td>{{_('Muito irritante e inutilizável')}}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- Audio -->
    <div class="row justify-content-md-center">
      <div class="col-md-6">
        <div class="shadow-sm card">
          <div class="card-header h3 text-center">
            {{_('Amostra')}} {{session['idx'] + 1}} {{_('de')}} {{max_lenth}}
          </div>
          <div class="card-body">
            <!-- Audio Player -->
            <div class="my-3 text-center">
              <audio controls="controls" preload="auto" id="audio_player">
                <source src="{{s3_client.generate_presigned_url('get_object', Params={'Bucket': audio_filepaths[session['idx']].bucket_name, 'Key': audio_filepaths[session['idx']].key}, ExpiresIn=3600)}}">
              </audio>
            </div>
            <!-- Audio Score -->
            <div class="text-center">
              <form method="POST">
                {{ vote_form.hidden_tag() }}
                <fieldset class="mb-3 form-group form-check-inline">
                  {% for score in vote_form.score %}
                    <div class="form-check form-check-inline">
                      {{ score(class="form-check-input", type="radio") }}
                      {{ score.label(class="form-check-label") }}
                    </div>
                  {% endfor %}
                </fieldset>
                <fieldset class="mb-3 form-group">
                  <!-- Previous button -->
                  {%if session['idx'] > 0%}
                    {{ page_form.submit_prev(class="btn btn-outline-primary btn-md") }}
                  {%endif%}
                  <!-- Next button -->
                  {{ vote_form.submit_next(class="btn btn-outline-primary btn-md") }}
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    {%else%}
    <div class="card shadow-sm ">
      <div class="card-body text-center">
        <div class="justify-content-center">
          {{_('Não há mais amostras a serem avaliadas. Agradecemos a sua participação!')}}
        </div>
      </div>
    </div>
  {%endif%}
{% endblock %}

app/templates/introduction.html
{% extends "base.html"%}
{% block content %}
  <div class="container">
    <div class="shadow card">
      <div class="card-body">
        <p class="mb-3 h1">{{_(Instruções)}}</p>
        <p>{{_('O <strong>Opinion Score (MOS)</strong> é a mais conhecida medida da qualidade de voz.
          É um método subjetivo de teste de qualidade. O Objetivo é avaliar a qualidade do
          áudio seguindo os critérios de compreensão do que está sendo falado e a
          presença de ruídos, que irritam/dificultam a compreensão da fala.')}}</p>
        <p>
          {{_('Você como avaliador deve dar uma nota para cada áudio, as notas variam
          de 1 a 5, como pode ser observado na tabela abaixo:')}}
        </p>

        <div class="container">
          <div class="row justify-content-md-center">
            <div class="col-md-6">
              <table class="shadow-sm table table-bordered bg-white">
                <thead>
                  <tr>
                    <th style="text-align:center">{{_('Avaliação')}}</th>
                    <th style="text-align:center">{{_('Qualidade')}}</th>
                    <th>{{_('Distorção')}}</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style="text-align:center">5</td>
                    <td>{{_('Excelente')}}</td>
                    <td>{{_('Imperceptível')}}</td>
                  </tr>

                  <tr>
                    <td style="text-align:center">4</td>
                    <td>{{_('Boa')}}</td>
                    <td>{{_('Apenas perceptível, mas não irritante')}}</td>
                  </tr>

                  <tr>
                    <td style="text-align:center">3</td>
                    <td>{{_('Razoável')}}</td>
                    <td>{{_('Perceptível e ligeiramente irritante')}}</td>
                  </tr>

                  <tr>
                    <td style="text-align:center">2</td>
                    <td>{{_('Pobre')}}</td>
                    <td>{{_('Irritante, mas não inutilizável')}}</td>
                  </tr>

                  <tr>
                    <td style="text-align:center">1</td>
                    <td>{{_('Ruim')}}</td>
                    <td>{{_('Muito irritante e inutilizável')}}</td>
                  </tr>

                </tbody>
              </table>
            </div>
          </div>
        </div>

        <ul>
          <li>
            {{_('A nota 1 (Ruim) deve ser dada quando o som possuir um alto
            nível de distorção, sendo muito irritante e não seja possível compreender o que
            está sendo falado.')}}
          </li>

          <li>
            {{_('A nota 2 (Pobre) deve ser dado a um áudio quando a
            distorção é irritante mas é possível entender o que está sendo falado.')}}
          </li>

          <li>
            {{_('A nota 3 (Razoável) deve ser atribuída a um áudio quando a distorção do sinal é
            perceptível e ligeiramente irritante.')}}
          </li>

          <li>
            {{_('A nota 4 (Boa) deve ser atribuída a um
            áudio onde a distorção é perceptível porém não é irritante.')}}
          </li>

          <li>
            {{_('A nota 5 (Excelente) deve ser atribuída para um áudio onde a distorção/ruído é imperceptível.')}}
          </li>
        </ul>

        <div class="p-3 text-center">
          <a href="{{ url_for('main.hello') }}" class="btn btn-outline-primary">{{_('Comece a avaliar')}}</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/sound_test.html
{% extends "base.html"%}
{% block content %}
  <div class="shadow card">
    <div class="card-body">
      <p class="mb-3 h1">{{_('Volume')}}</p>
      <p>{{_('Reproduza o áudio abaixo para testar o seu volume. Avance quando estiver satisfeito.')}}</p>
      <div class="mb-3 text-center">
        <audio controls="controls" preload="auto" id="audio_player">
          <source src="{{s3_client.generate_presigned_url('get_object', Params={'Bucket': os.environ.get('S3_BUCKET_SOUND_TEST'), 'Key': os.environ.get('S3_KEY_SOUND_TEST')}, ExpiresIn=3600)}}">
        </audio>
      </div>

      <div class="p-3 text-center">
        <a href="{{ url_for('main.introduction') }}" class="btn btn-outline-primary">{{_('Avançar')}}</a>
      </div>
    </div>
  </div>
{% endblock %}